# NOSONAR
FROM --platform=linux/amd64 python:3.12-slim

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1 \
    PIP_DISABLE_PIP_VERSION_CHECK=1 \
    PIP_NO_CACHE_DIR=1

WORKDIR /app

RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential ca-certificates curl git \
    libcairo2 libpango-1.0-0 libpangocairo-1.0-0 \
    libpangoft2-1.0-0 libharfbuzz-subset0 \
    fontconfig fonts-dejavu-core \
    && fc-cache -f \
    && rm -rf /var/lib/apt/lists/*

COPY pyproject.toml README.md manage.py /app/
COPY config /app/config
COPY apps /app/apps
COPY requirements /app/requirements
COPY scripts /app/scripts

RUN pip install --upgrade pip \
    && GIT_SSL_NO_VERIFY=true pip install -r /app/requirements/local.txt \
    && pip install debugpy==1.8.5

EXPOSE 8000 5678
